/*
 * Copyright (C) 2003 HawkinsSoftware
 *
 * This prototype of the Decaf Java development environment is free 
 * software.  You can redistribute it and/or modify it under the terms 
 * of the GNU General Public License as published by the Free Software 
 * Foundation.  However, no compilation of this code or a derivative
 * of it may be used with or integrated into any commercial application,
 * except by the written permisson of HawkinsSoftware.  Future versions 
 * of this product will be sold commercially under a different license.  
 * HawkinsSoftware retains all rights to this product, including its
 * concepts, design and implementation.
 *
 * This prototype is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */
 
package com.bitwise.umail;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.16u-20021014-2200
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class uMailJNI {
  public final static native boolean uIterator_hasNext(long jarg1);
  public final static native Object uIterator_next(long jarg1);
  public final static native long uIterator_getNext(long jarg1);
  public final static native void uIterator_remove(long jarg1);
  public final static native void delete_uIterator(long jarg1);
  public final static native String jString_get(long jarg1);
  public final static native long new_jString();
  public final static native void delete_jString(long jarg1);
  public final static native long new_jHandle();
  public final static native String jHandle_getMethodName(long jarg1);
  public final static native String jHandle_getPluginName(long jarg1);
  public final static native String jHandle_getDescription(long jarg1);
  public final static native long jHandle_getParameterTypes(long jarg1);
  public final static native void jHandle_setPluginName(long jarg1, String jarg2);
  public final static native void delete_jHandle(long jarg1);
  public final static native String jType_unqualifiedName(long jarg1);
  public final static native long jType_getContent(long jarg1);
  public final static native long new_jType();
  public final static native void delete_jType(long jarg1);
  public final static native int jTime_getSecond(long jarg1);
  public final static native int jTime_getMinute(long jarg1);
  public final static native int jTime_getHour(long jarg1);
  public final static native int jTime_getDay(long jarg1);
  public final static native int jTime_getMonth(long jarg1);
  public final static native int jTime_getYear(long jarg1);
  public final static native boolean jTime_isDST(long jarg1);
  public final static native long new_jTime();
  public final static native void delete_jTime(long jarg1);
  public final static native void jPluginLib_init(long jarg1);
  public final static native void jPluginLib_log(String jarg1);
  public final static native String jPluginLib_getClasspath();
  public final static native long new_jPluginLib();
  public final static native void delete_jPluginLib(long jarg1);
  public final static native long new_jMessage(long jarg1);
  public final static native long jMessage_getFrom(long jarg1);
  public final static native long jMessage_getTo(long jarg1);
  public final static native String jMessage_getSubject(long jarg1);
  public final static native String jMessage_getBody(long jarg1);
  public final static native void jMessage_setTo(long jarg1, String jarg2);
  public final static native void jMessage_setSubject(long jarg1, String jarg2);
  public final static native void jMessage_setBody(long jarg1, String jarg2);
  public final static native long jMessage__getSentTime(long jarg1);
  public final static native void delete_jMessage(long jarg1);
  public final static native long new_jAddressee(long jarg1);
  public final static native String jAddressee_getAddress(long jarg1);
  public final static native void delete_jAddressee(long jarg1);
  public final static native long new_jFolder__SWIG_0(long jarg1);
  public final static native long new_jFolder__SWIG_1(String jarg1);
  public final static native String jFolder_getName(long jarg1);
  public final static native void jFolder_add__SWIG_0(long jarg1, long jarg2);
  public final static native void jFolder_add__SWIG_1(long jarg1, long jarg2);
  public final static native long jFolder_getSubFolder__SWIG_0(long jarg1, String jarg2);
  public final static native long jFolder_getSubFolder__SWIG_1(long jarg1, String jarg2, boolean jarg3);
  public final static native void jFolder_remove(long jarg1, int jarg2);
  public final static native int jFolder_getSize(long jarg1);
  public final static native long jFolder_getMessages(long jarg1);
  public final static native long jFolder_getParent(long jarg1);
  public final static native long jFolder_getSubFolders(long jarg1);
  public final static native void delete_jFolder(long jarg1);
  public final static native long new_jAccount(long jarg1);
  public final static native long jAccount_getRoot(long jarg1);
  public final static native long jAccount_getUser(long jarg1);
  public final static native void jAccount_log(long jarg1, String jarg2);
  public final static native void delete_jAccount(long jarg1);
  public final static native long new_jMenu(long jarg1);
  public final static native int jMenu_getSize(long jarg1);
  public final static native void jMenu_go(long jarg1);
  public final static native void jMenu_append(long jarg1, long jarg2);
  public final static native void delete_jMenu(long jarg1);
  public final static native long new_jMenuOption__SWIG_0(long jarg1);
  public final static native long new_jMenuOption__SWIG_1(String jarg1, String jarg2);
  public final static native String jMenuOption_getDisplayText(long jarg1);
  public final static native void delete_jMenuOption(long jarg1);
  public final static native long new_jFolderMenuOption__SWIG_0(long jarg1);
  public final static native long new_jFolderMenuOption__SWIG_1(String jarg1, long jarg2);
  public final static native String jFolderMenuOption_getDisplayText(long jarg1);
  public final static native void delete_jFolderMenuOption(long jarg1);
  public final static native long new_jMessageMenuOption__SWIG_0(long jarg1);
  public final static native long new_jMessageMenuOption__SWIG_1(String jarg1, long jarg2);
  public final static native String jMessageMenuOption_getDisplayText(long jarg1);
  public final static native void delete_jMessageMenuOption(long jarg1);
  public final static native long new_jFolderMenuPlugin__SWIG_0(long jarg1);
  public final static native long new_jFolderMenuPlugin__SWIG_1(String jarg1, long jarg2, String jarg3);
  public final static native String jFolderMenuPlugin_getDisplayText(long jarg1);
  public final static native void delete_jFolderMenuPlugin(long jarg1);
  public final static native long new_jPrompt__SWIG_0(long jarg1);
  public final static native long new_jPrompt__SWIG_1(String jarg1, boolean jarg2);
  public final static native String jPrompt_askUser__SWIG_0(long jarg1);
  public final static native String jPrompt_askUser__SWIG_1(long jarg1, String jarg2);
  public final static native void delete_jPrompt(long jarg1);
  public final static native long new_jMessageInput(long jarg1);
  public final static native long jMessageInput_getToPrompt(long jarg1);
  public final static native long jMessageInput_getSubjectPrompt(long jarg1);
  public final static native long jMessageInput_getBodyPrompt(long jarg1);
  public final static native long jMessageInput_getMessage(long jarg1);
  public final static native void delete_jMessageInput(long jarg1);
  public final static native long new_jDataDisplay(long jarg1);
  public final static native void jDataDisplay_setLabel(long jarg1, String jarg2);
  public final static native void jDataDisplay_setValue(long jarg1, String jarg2);
  public final static native void jDataDisplay_display(long jarg1);
  public final static native void delete_jDataDisplay(long jarg1);
  public final static native long new_jMessageDisplay(long jarg1);
  public final static native long jMessageDisplay_getFrom(long jarg1);
  public final static native long jMessageDisplay_getSubject(long jarg1);
  public final static native long jMessageDisplay_getBody(long jarg1);
  public final static native long jMessageDisplay_getSentTime(long jarg1);
  public final static native long jMessageDisplay_getMessage(long jarg1);
  public final static native void jMessageDisplay_initValues(long jarg1);
  public final static native void jMessageDisplay_align(long jarg1);
  public final static native void delete_jMessageDisplay(long jarg1);
  public final static native long new_List();
  public final static native void List_append(long jarg1, long jarg2);
  public final static native int List_getSize(long jarg1);
  public final static native long List_iterator(long jarg1);
  public final static native void List_shrink(long jarg1);
  public final static native void delete_List(long jarg1);
  public final static native boolean ListIterator_hasNext(long jarg1);
  public final static native Object ListIterator_next(long jarg1);
  public final static native long ListIterator_getNext(long jarg1);
  public final static native void ListIterator_remove(long jarg1);
  public final static native long new_ListIterator();
  public final static native void delete_ListIterator(long jarg1);
  public final static native long new_jVector();
  public final static native Object jVector_get(long jarg1, int jarg2);
  public final static native void jVector_set(long jarg1, int jarg2, Object jarg3);
  public final static native void jVector_add(long jarg1, Object jarg2);
  public final static native void jVector_remove(long jarg1, int jarg2);
  public final static native int jVector_getSize(long jarg1);
  public final static native long jVector_iterator(long jarg1);
  public final static native void delete_jVector(long jarg1);
  public final static native long SWIGjMessageTojType(long jarg1);
  public final static native long SWIGjAddresseeTojType(long jarg1);
  public final static native long SWIGjFolderTojType(long jarg1);
  public final static native long SWIGjAccountTojType(long jarg1);
  public final static native long SWIGjMenuTojType(long jarg1);
  public final static native long SWIGjMenuOptionTojType(long jarg1);
  public final static native long SWIGjFolderMenuOptionTojType(long jarg1);
  public final static native long SWIGjMessageMenuOptionTojType(long jarg1);
  public final static native long SWIGjFolderMenuPluginTojType(long jarg1);
  public final static native long SWIGjPromptTojType(long jarg1);
  public final static native long SWIGjMessageInputTojType(long jarg1);
  public final static native long SWIGjDataDisplayTojType(long jarg1);
  public final static native long SWIGjMessageDisplayTojType(long jarg1);
  public final static native long SWIGListIteratorTouIterator(long jarg1);
}
